# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-session-stack}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jun Kikuchi"]
  s.date = %q{2009-09-27}
  s.description = %q{rack-session-stack}
  s.email = %q{kikuchi@bonnou.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
     "COPYING",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rack-session-stack.rb",
     "lib/rack-session-stack/memcache.rb",
     "lib/rack-session-stack/raws/sdb.rb",
     "lib/rack-session-stack/sequel.rb"
  ]
  s.homepage = %q{http://github.com/JunKikuchi/rack-session-stack}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{rack-session-stack}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<uuidtools>, [">= 2.0.0"])
    else
      s.add_dependency(%q<uuidtools>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<uuidtools>, [">= 2.0.0"])
  end
end
